### ISSUE TITLE
file_name and file_orginalFile as a header is not found in file-source

### ISSUE THREAD

**Issue by brijesh1100** [spring-cloud-stream-app-starters/file#9]
I am using file-source with s3 sink, I want to use this header to upload the file to S3 with the same name.
I can see a few headers (like Content-Type, id and timestamp) but file_name in header is not found.
I was assigning the `key-expression = "headers['file_name']"` but I get an error message that such header does not exist.
Can you tell me what is the `issue`, as I can see in this doc https://github.com/spring-cloud-stream-app-starters/file/tree/master/spring-cloud-starter-stream-source-file
if we take mode as 
`mode = contents`
Headers should come these:
`Content-Type: application/octet-stream`
`file_orginalFile: <java.io.File>`
`file_name: <file name>`

**Comment by brijesh1100** [comment]
@sobychacko , @artembilan

**Comment by artembilan** [comment]
The `file_orginalFile` is a typo. Must be `file_originalFile` - exactly what we have with the `FileHeaders.ORIGINAL_FILE` constant. Must be fixed. I did similar fix yesterday for the SFTP source: https://github.com/spring-cloud-stream-app-starters/sftp/commit/bb4cf17ba99bbe2e031585f73d1a2ec07e412f44


The `FileReadingMessageSource` has started to populate those headers from Spring Integration `5.0`: https://jira.spring.io/browse/INT-832. So, yes, that README is misleading a bit.

Unfortunately I don't see any workaround for the current state, unless you copy/paste the `FileSourceConfiguration` content to your own class and extend a `fileSourceFlow()` to the `.enrcichHeaders()`.

Meanwhile I'm fixing the `master` for SCSt 2.0...

**Comment by brijesh1100** [comment]
Thanks @artembilan,
what about `file_name` this is also not coming in headers any luck we can do this fix.
my main concern is I have to extract file_name from headers, so please tell me any work around regarding so I can add in my code.

**Comment by artembilan** [comment]
As I said: the only one workaround I see is like code your own `Source` and populate such a header manually downstream already after `FileReadingMessageSource`. And only after that send the message with content and appropriate header to the target destination.

**Comment by brijesh1100** [comment]
sure @artembilan will do

**Comment by artembilan** [comment]
The Pull Request for this issue provides a test-case when we verify that mentioned headers already come with the output message. 
When it will be merged and you are able to switch to the `2.0` version for SCSt, you'll get requested functionality for free.

**Comment by gslulu** [comment]
Does the integration on Mar 22 mean that file_name, file_orginalFile, and Content-Type are available in the latest SNAPSHOT? I still can't see it working.

The versions I'm using:
spring-cloud-dataflow-server-local-1.4.0.RELEASE.jar
file-source-rabbit-1.3.1.BUILD-SNAPSHOT

**Comment by artembilan** [comment]
No, you have to use `file-source-rabbit-2.0.0.RELEASE`.
Please, read comments here carefully.

**Comment by gslulu** [comment]
Sorry, for your quick response. 
I was confused because the scs app starter home page (https://cloud.spring.io/spring-cloud-stream-app-starters/) listed 1.3.1 as the latest snapshot release. I'm good now. Thank You.
